FROM python:3.11-slim

WORKDIR /app

ENV TMPDIR=/tmp
ENV PIP_NO_CACHE_DIR=1

COPY requirements.txt .

RUN mkdir -p /tmp && chmod 1777 /tmp

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]